micronaut:
    application:
        name: Leika

endpoints:
    info:
        enabled: true
        sensitive: false
    health:
        enabled: true

redis:
    uri: "redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}"

